var conc = ["???Stormwater Management",
"Ability to Work",
"Abiotic State",
"Access to Education",
"Access to Health Care",
"Access to Healthy Food",
"Access to Housing",
"Access to Jobs",
"Access to Open Space & Recreational Opportunities",
"Access to Transportation",
"Accidental & Illegal Harvest",
"Accidental Introduction of Non-Native Species",
"Acid Deposition",
"Acquisition of Goods",
"Administration of Economic Programs",
"Administration of Education Programs",
"Administration of Energy Policy & Programs",
"Administration of Environmental Quality",
"Administration of Green Infrastructure Programs",
"Administration of Housing & Urban Development",
"Administration of Human Resources",
"Administration of Public Health Programs",
"Administration of Transportation",
"Advertisement & Promotion",
"Aesthetic or Sensory Value",
"Age Demographics & Distribution",
"Aging Structures",
"Agricultural Habitat",
"Agricultural Land",
"Agriculture",
"Agriculture BMPs",
"Air & Climate Regulation",
"Air Emissions Regulations",
"Air Quality",
"Air Quality Regulation",
"Air Temperature",
"Air Transportation Infrastructure",
"Air travel",
"Air-Based Spatial Resources",
"Algae",
"Algal Blooms",
"Allergens",
"Allergies",
"Alternative Energy Sources",
"Alternative Scenarios",
"Alternatives to Toxic Substances",
"Amphibians",
"Anemones",
"Animal Feeding Operations",
"Animal Production",
"Animal Skins & Fur",
"Animals",
"Anthozoa",
"Apex Fish Predators",
"Applied Chemicals",
"Appreciation of Beauty & Aesthetics",
"Appreciation of Nature",
"Aquaculture",
"Aquaculture Stock",
"Aquaculture/Mariculture BMPs",
"Aquarium & Pet Trade",
"Aquarium Stock",
"Aquatic Acidity",
"Aquatic Debris",
"Aquatic Habitat",
"Aquatic Habitat Modification",
"Aquatic Hypoxia",
"Aquatic Plants",
"Aquatic Resources",
"Aquatic Species",
"Aquifer Recharge",
"Aquifer Storage",
"Arctic Habitat",
"Arctic Plants",
"Arctic Species",
"Artificial Habitat",
"Artisanal Fishing",
"Artistic Trades",
"Assessment & Analysis",
"Assessment, Decision Support, Research & Development",
"Asthma",
"Atmosphere",
"Atmospheric Emissions",
"Atmospheric Phenomena",
"Autoimmune Diseases",
"Available Freshwater",
"Bacteria",
"Ballast Discharge",
"Banks, Credit, Securities",
"Barren Rock & Sand",
"Benthic Macroinvertebrates",
"Benthos",
"Bicycle Transportation Infrastructure",
"Bicycling",
"Biochemical Resources",
"Biodiversity",
"Biofuel",
"Biofuels",
"Biological Addition",
"Biological Harvest",
"Biological Raw Materials",
"Bio-Remediation",
"Biotechnology Research & Development",
"Biotic State",
"Birds",
"Bivalves",
"Body Systems",
"Bone Strength & Function",
"Boring Sponges",
"Broadcasting",
"Brownfield",
"Budget & Fiscal Resources",
"Building & Home Construction & Maintenance",
"Building Heat",
"Building Materials",
"Built or Constructed Environment",
"Cadmium Concentration in Body",
"Calcareous Macroalgae",
"Calcium Carbonate Deposition",
"Cancer",
"Car & Boat Rental Services",
"Carbon Dioxide (CO2)",
"Carbon Dioxide (CO2) Emission",
"Carbon Monoxide",
"Carbon Storage & Cycling",
"Certification",
"Characterization & Classification",
"Chemical & Metal Contaminants",
"Chemical Products",
"Chemical Use Regulations",
"Chemical Variables",
"Chlorofluorocarbon (CFC) Emission",
"Choice of Community or Neighborhood",
"Citizen Engagement",
"Civic Organizations",
"Civic Satisfaction",
"Civil Engineering & Construction",
"Cleaner & Solvent Use",
"Cleanup of Parks or Other Inland Sites",
"Cleanup sites",
"Climate",
"Climate Change",
"Climbing",
"Coal Combustion",
"Coal Mining",
"Coal Products",
"Coal Reserves",
"Coastal Animals",
"Coastal Benthic Communities",
"Coastal Bulkheads (Seawalls)",
"Coastal Cleanups",
"Coastal Damage",
"Coastal Defense",
"Coastal Development",
"Coastal Embayments",
"Coastal Engineering & Construction",
"Coastal Habitat",
"Coastal Identity",
"Coastal Land Loss",
"Colleges, Professional & Technical Schools",
"Combined Sewer Overflows (CSOs)",
"Commercial Development",
"Commercial Fishing",
"Commercial Fishing Boats",
"Commercial/Residential Mix",
"Communities",
"Community & Neighborhood Non-Profit Organizations",
"Community Diversity & Distribution",
"Community Identity",
"Community or Stakeholder Engagement",
"Community Population Size",
"Community Vibrancy",
"Compassion & Desire for Fairness",
"Competition",
"Complex Habitat & Resources",
"Comprehensive or Management Plans",
"Concentrated Solar Thermal Plants",
"Concentrations of Toxins in Body",
"Concern for the Environment",
"Connection with the Natural World",
"Conservation, Restoration, & Ecosystem Management",
"Consumption Patterns",
"Consumption Quantity",
"Contact Uses",
"Contaminant Discharge",
"Contaminant Processing",
"Contaminant Runoff",
"Controlled Biological Introductions",
"Convention & Visitors Centers",
"Cooling Water Discharge",
"Coral",
"Coralline Algae",
"Corallivorous Fish",
"Cotinine Concentration in Body",
"Crop Production",
"Crops",
"Crowding",
"Cruise Ships",
"Cultural & Social Well-Being",
"Cultural Identity",
"Cultural Resources",
"Cyanobacteria",
"Cyanotoxins",
"Dam Construction & Maintenance",
"Damage from Anchoring & Vessel Grounding",
"Damage from Boat Gear",
"Damage from Boat Movement",
"Damage from Boating Activities",
"Damage from Trawling & Fishing Gear",
"Data Access & Management",
"Debris",
"Decision Support Tools",
"Decomposers",
"Deforestation & Devegetation",
"Demonstration or Pilot Projects",
"Desalination Plants",
"Desert Habitat",
"Desert Plants",
"Desert Species",
"Diabetes",
"Dilution of Toxins or Pollutants",
"Discharge & Emissions Limitations",
"Discharges",
"Disease Regulation",
"Disease Vectors",
"Dissolved Oxygen in Water",
"Ditching & Soil Disturbance",
"Dive, Snorkeling & Swimming Tourism",
"Dock & Marina Construction & Maintenance",
"Dolphin Poaching or Harvest",
"Domestic Animal Waste",
"Drainage",
"Dredging, Draining & Filling",
"Drinkable Water",
"Drinking Water Management",
"Drivers",
"Drought",
"Drug-Resistant Pathogens",
"Dung",
"Durable Goods Suppliers",
"Earthquakes",
"Eating Habits",
"Ecological Abundance & Population Density",
"Ecological Attributes",
"Ecological Connectivity",
"Ecological Integrity",
"Ecological Mutualism & Commensalism",
"Ecological Process",
"Ecological Resilience & Thresholds",
"Ecological Vulnerability to Climate Change",
"Ecological Vulnerability to Human Activities",
"Ecological Vulnerability to Pollution",
"Ecological Vulnerability to Stressors",
"Economic Demographics & Distribution",
"Economic Markets & Policies",
"Economic Productivity",
"Economic Prosperity",
"Economic State",
"Ecosystem Management",
"Ecosystem Services",
"Education & Information",
"Education or Visitor Centers",
"Education Policies & Programs",
"Education, Outreach & Engagement",
"Educational Attainment",
"Educational Attainment Demographics & Distribution",
"Educational Disparity",
"Educational Value",
"El Nino/Southern Oscillation (ENSO)",
"Electric Power Available",
"Electricity Use",
"Electronics & Electric Equipment Manufacturing",
"Elementary & Secondary Schools",
"Elevation",
"Eliciting Public Perspectives or Information",
"Emergency Response",
"Employment",
"Encrusting Sponges",
"Endocrine System",
"Endowment for Future Generations",
"Energy Industry",
"Energy Policies & Programs",
"Energy Resources Management",
"Energy Use",
"Enforcement of Justice & Public Order",
"Entertainment & Accomodation Services",
"Environmental Cleanup/Remediation & Emergency Response",
"Environmental Management Plans",
"Environmental Policies and Programs",
"Environmental Restoration",
"Environmental State",
"Equity",
"Erosion",
"Estuaries",
"Ethnic Identity",
"Eutrophication",
"Exercise",
"Exhibits, Tours & Seminars",
"Existence & Intrinsic Value",
"Exposure to Nuisances",
"Exposure to Risk",
"Exposure to Toxins",
"Extracts",
"Family Dynamics",
"Fecal coliform",
"Federal Tax Revenue",
"Fertilizer Use",
"Fibers & Resins",
"Filtration of Toxins or Pollutants",
"Finance & Insurance",
"Finfish Harvest",
"Fire",
"Fish",
"Fishing & Hunting",
"Fishing Sector",
"Fishing Stock",
"Fishing, Harvesting & Hunting Management",
"Fleshy Macroalgae",
"Flooding",
"Floodplain Development",
"Fodder & Fertilizer",
"Food & Agriculture Policies & Programs",
"Food & Raw Materials Sectors",
"Food Resources",
"Food, Beverage & Tobacco Products",
"Forest Species",
"Forestry",
"Forestry Harvest",
"Forests",
"Fossil Fuel Reserves",
"Fossil Fuels",
"Freedom from Pain & Suffering",
"Freight Rail Infrastructure",
"Freshwater Diversions",
"Freshwater Fish",
"Freshwater Habitat",
"Freshwater Quantity",
"Fuel",
"Fuelwood & Charcoal",
"Funding & Incentives",
"Fungi",
"Gastrointestinal System",
"Gender",
"Gender Demographics & Distribution",
"Generosity & Desire to Help Others",
"Genes",
"Genetic Diversity",
"Genetic Resources",
"Genetically Modified Crops",
"Genetically Modified Foods",
"Genetically Modified Organisms",
"Geothermal Power",
"Geysers",
"Global Climate Regulation",
"Golf Courses",
"Governance",
"Government Funding",
"Grantmaking Organizations",
"Grants & Funding from Federal Government",
"Grants & Funding from Local Government",
"Grants & Funding from Private Sources",
"Grants & Funding from State Government",
"Grasslands Habitat",
"Grasslands Species",
"Green Infrastructure",
"Green Infrastructure (GI) & Low Impact Development (LID)",
"Greenhouse Gas Emissions",
"Greenhouse Gases",
"Ground Level Ozone",
"Groundwater Availability",
"Groundwater Depletion",
"Groundwater Quality",
"Growth",
"Happiness & Fulfillment",
"Hazardous Spills",
"Hazardous Wastes",
"Health & Safety",
"Health Disparity",
"Health Policies & Programs",
"Health Sector",
"Heart Disease",
"Heat & Electric Utilities",
"Heat Stress",
"Herbicide Use",
"Historic Sites & Structures",
"Homeownership and Landownership Choices",
"Hotel & Food Services",
"Household Conservation Choices",
"Household Financial Choices",
"Household Products",
"Household Spending Power",
"Household Waste Disposal Choices",
"Housekeeping",
"Housing Affordability",
"Housing Choice",
"Housing Development",
"Housing Stock",
"Human Behavior",
"Human Illness or Disease",
"Human Needs Sectors",
"Human Population Demographics & Distribution",
"Human Population Density & Distribution",
"Human State",
"Human Vulnerability to Natural Disaster",
"Human Well-Being",
"Hunting Sector",
"Hunting Stock & Wild Foods",
"Hydrocarbons",
"Hydrocoral",
"Hydroelectric Power",
"Hydrologic Cycle",
"Hydrologic or Hydraulic  Modifications",
"Illicit Discharge Detection & Elimination",
"Immune System",
"Impacts",
"Impervious Surface Runoff",
"Impervious Surfaces",
"Income",
"Indicators & Metrics",
"Individual & Family Behavior",
"Individual Consumption Choices",
"Individual Health Care Choices",
"Individuals",
"Indoor Air Quality",
"Industrial Development",
"Industrial Facilities",
"Industrial Wastes",
"Infrastructure",
"Infrastructure & Buildings Management & Planning",
"Infrastructure for Transport of Goods",
"Infrastructure for Transport of Humans",
"Inorganic Toxins",
"Insect Pests & Pest Predators",
"Insects",
"Instream Temperatures",
"Instruction & Training",
"Insurance",
"International Affairs",
"Internet & Telecommunications Utilities",
"Invasive Animals",
"Invasive Aquatic Species",
"Invasive Plants",
"Invasive Species",
"Invertebrate Harvest",
"Invertivorous Fish",
"Investigation & Security Services",
"Irrigation",
"Issue-Specific Education & Outreach",
"Justice & Law Enforcement",
"Knowledge Value",
"Lakes & Ponds",
"Land Abandonment",
"Land Acquisition & Protection",
"Land Development",
"Land Subsidence",
"Land Transportation Infrastructure",
"Land-Based Civil Engineering & Construction",
"Land-based Damage",
"Land-Based Spatial Resources",
"Landfill",
"Landscape Changes",
"Landscaping & Household Services",
"Landuse Management & Smart Growth",
"Landuse Management & Urban/Regional Planning",
"Large Herbivorous Fish",
"Large Ships",
"Lead Concentration in Body",
"Legal & Accounting Services",
"Libraries",
"Life Span",
"Life Stage",
"Lifestyle",
"Lifestyle Choices",
"Light",
"Littering",
"Live Collection",
"Livestock",
"Living Habitat",
"Lobster, Crab & Shrimp",
"Local Tax Revenue",
"Love",
"Low Birth Weight Infants",
"Lyme Disease",
"Machinery Manufacturing",
"Management of Companies",
"Management of Mining and Mined Materials",
"Manatee Poaching or Harvest",
"Manatees",
"Mangroves",
"Manufacturing & Trade",
"Marine Birds",
"Marine Habitat",
"Marine Invertebrates",
"Marine Mammal Poaching or Harvest",
"Marine Mammals",
"Marine Shipping Industry",
"Marine Species",
"Marine Worms",
"Marketing & Publicity",
"Mass Stabilization & Erosion Control",
"Materials Use",
"Mediation of Noise",
"Mediation of Odors",
"Mediation of Waste, Toxics & Other Nuisances",
"Medical Care",
"Medical Centers",
"Medical Equipment Manufacturing",
"Medical or Insurance Costs/Affordability",
"Mental & Cognitive Health",
"Mercury Compounds",
"Mercury Concentration in Body",
"Metals Emission",
"Metals, Electronics & Machinery Products",
"Methane (CH4) Emission",
"Micro & Regional Climate Regulation",
"Microorganisms",
"Military",
"Mineral Products",
"Mineral, Rock, & Metal Mining",
"Mining",
"Mobility",
"Modeling",
"Monitoring & Evaluation",
"Motion Picture & Music",
"Motor Vehicle Manufacturing & Retail",
"Multi-Unit Housing",
"Municipal Wastes",
"Munitions",
"Museums, Amusement Parks & Historical Sites",
"Mycorrhizae",
"National Defense",
"Natural Disasters",
"Natural Gas Combustion",
"Natural Gas Reserves",
"Natural Gas Utilities",
"Natural Hazard Protection",
"Natural Medicines",
"Navigable Water",
"Neurologic Diseases",
"Neurological System",
"Nitrogen",
"Nitrogen fixers",
"Nitrogen Fixing",
"Nitrogen Oxide (NOx) Emission",
"Nitrogen Oxides (Nox)",
"Nitrous Oxide (N2O) Emission",
"Noise Pollution",
"Nondurable Goods Suppliers",
"Non-Methane Hydrocarbon Emission",
"Non-Point Source Controls",
"Non-Point Source Runoff",
"Non-Profit Organizations",
"Nursery Habitat",
"Nutrient Cycling",
"Nutrient Discharge",
"Nutrient Runoff",
"Nutrients",
"Obesity",
"Ocean Acidity",
"Ocean Circulation & Flow",
"Octocoral",
"Octopus & Squid",
"Odors",
"Oil & Gas Extraction",
"Oil & Gas Industry",
"Oil & Gas Pipelines",
"Oil & Gas Research & Exploration",
"Oil & Gas Rigs",
"Oil & Gas Tankers",
"Oil & Gas Transport",
"Oil Combustion",
"Oil Reserves",
"Oil Utilities",
"Open Ocean & Seas",
"Open Space",
"Open Space Management",
"Organic Toxins",
"Ornamental Jewelry & Art",
"Ornamental Resources",
"Outdoor Air Quality",
"Outreach to Learning Institutions",
"Ozone Delpleting Substances",
"Parking Infrastructure",
"Parking Lots",
"Particulate Matter",
"Particulates Emissions",
"Passenger Rail Infrastructure",
"Pathogens",
"Pedestrian Transportation Infrastructure",
"Perception of safety",
"Persistent Organic Pollutants Concentration in Body",
"Personal Care & Cosmetics Products",
"Personal Characteristics",
"Personal Hygiene",
"Personal Injury",
"Pest Regulation",
"Pesticide & Insecticide Use",
"Pesticide Concentration in Body",
"Pesticides",
"Pet Ownership",
"Petroleum Products",
"Petroleum Spills",
"Pharmaceutical Products",
"Pharmaceuticals & Cosmetics Sources",
"Phosphorus",
"Phthalates Concentration in Body",
"Physical Damage",
"Physical Variables",
"Pipeline Construction",
"Piscivorous Fish",
"Planktivorous Fish",
"Plankton & Zooplankton",
"Plant Harvest",
"Plants",
"Plastics & Rubber Products Manufacturing",
"Point & Mobile Source Controls",
"Point Source Discharges",
"Policy Evaluation",
"Pollination",
"Port & Harbor Construction & Maintenance",
"Postal Service",
"Poverty Demographics & Distribution",
"Power Plants",
"Prairie Habitat",
"Prairie Species",
"Precipitation",
"Predation & Grazing",
"Presence of Nature",
"Preservation of History or Heritage",
"Pressures",
"Primary & Fabricated Metals Products",
"Primary Production",
"Product Choice",
"Professional Services Sectors",
"Property Values",
"Provisioning Services",
"Public Administration",
"Public Opposition or Support",
"Public Policy Administration",
"Public Relations Services",
"Public Space",
"Public Stewardship",
"Public Transit Infrastructure & Fleets",
"Public Transit Ridership",
"Public Utility Policies",
"Public-Private Partnerships",
"Published Outreach & Education Materials",
"Publishing",
"Race Demographics & Distribution",
"Race or Ethnicity",
"Rail Transportation Infrastructure",
"Real Estate",
"Recreational Fishing",
"Recreational Value",
"Recycling",
"Reef Fish",
"Reef Habitat",
"Reef Invertebrates",
"Reef Species",
"Reef Structural Strength",
"Reforestation",
"Regional Planning",
"Regulating Services",
"Religious Affiliation",
"Religious Identity",
"Religious Organizations & Places of Worship",
"Remediation & Recovery Services",
"Renal (Kidney)  Function",
"Rental & Leasing",
"Repair & Maintenance Services",
"Reproduction",
"Reproductive System",
"Reptile, Turtle, or Amphibian Poaching or Harvest",
"Research Potential",
"Resource Use",
"Resource Use Management",
"Respiratory Illness",
"Respiratory System",
"Responses",
"Revitalization & Urban Renewal",
"Road Construction & Maintenance",
"Road Development",
"Road Transportation & Congestion",
"Road Transportation Infrastructure",
"Roadway Distribution",
"Role of Decision Makers",
"Rooftop Photovoltaic (PV) Panels",
"Rural Identity",
"Salinity",
"Salt Marsh Fishes",
"Sand, Rock & Land Formation",
"Sandy Beaches",
"Scenic Transportation",
"Schools & Colleges",
"Schools, Parks & Playgrounds",
"Scientific Research & Development",
"Scrubland/Shrubland",
"Sea Ice Albedo",
"Sea Temperature",
"Sea Turtles",
"Sea Urchins",
"Seagrasses",
"Seastars (Starfish)",
"Secure Home",
"Security",
"Security Policies & Programs",
"Sediment Accumulation",
"Sediment Discharge",
"Sediment Diversions",
"Sediment Resuspension",
"Sediment Runoff",
"Selenium Compounds",
"Self Care",
"Sense of Belonging",
"Sense of Place",
"Septic Systems",
"Sequestration/Storage/Accumulation of Toxins or Pollutants",
"Sewer Line Construction & Maintenance",
"Shellfish",
"Shellfish Harvest",
"Shellfish Stock",
"Shipping Channels",
"Shipping, Warehousing & Storing",
"Shoreline Alteration",
"Shoreline Armoring",
"Shoreline Protection",
"Sick Days",
"Single Family Housing",
"Site Remediation",
"Site-Scale Planning, Design, & Development",
"Size, Height & Width",
"Skills, Knowledge & Experience",
"Small & Recreational Boats",
"Small Herbivorous Fish",
"Smoking",
"Snails & Conch",
"Snow & Ice",
"Social Drivers",
"Social Group",
"Social Media",
"Social Relations",
"Social Resilience & Adaptive Capacity",
"Social Support",
"Socio-Cultural Policies & Protections",
"Socio-Economic Status",
"Soil & Sediment Stabilization",
"Soil pH",
"Soil Production",
"Soil Quality Regulation",
"Soils",
"Solar Hot Water Heaters",
"Solar Power",
"Solid Waste Disposal & Recycling Services",
"Solid Waste Disposal Sites",
"Souvenir & Decorative Trade",
"Space Resources",
"Specialty Trade Construction",
"Spiritual Fulfillment",
"Sponges",
"Sprawl",
"Standards, Codes, Permitting & Zoning",
"State",
"State Tax Revenue",
"Stony Coral",
"Storms & Hurricanes",
"Storm-Surge & Flood Protection",
"Stormwater Management",
"Stormwater Retention",
"Stratification",
"Stratospheric Ozone",
"Streams & Rivers",
"Street Design & Patterns",
"Structural Diversity",
"Structural Habitat",
"Structure & Stabilization",
"Subsistence",
"Subsistence Clothing/Warmth",
"Subsistence Food & Cooking",
"Subsistence Fuel",
"Subsistence Housing & Infrastructure",
"Substrate",
"Substrate Stability",
"Sulfur Dioxide",
"Sulfur Oxide (Sox) Emission",
"Sunscreen Use",
"Supplemental Feeding",
"Supporting Services",
"Surface & Groundwater Flow",
"Surface Permeability",
"Surface Water Quality",
"Survival & Mortality",
"Sustainable Resource Use",
"Swimmable Water",
"Symbolic Value",
"Tax Revenue",
"Technical Assistance",
"Technology Improvements & Innovations",
"Tenancy",
"Terrestrial Debris & Litter",
"Terrestrial Habitat",
"Terrestrial Mammals",
"Terrestrial Plants",
"Terrestrial Reptiles",
"Terrestrial Species",
"Terrestrial Worms",
"Textiles & Apparel",
"Timber & Wood Fiber",
"Tolerance",
"Topography & Bathymetry",
"Tourism & Recreation",
"Tourism & Recreation Policies & Programs",
"Toxic Metals",
"Toxins",
"Trainings or Workshops",
"Trampling",
"Transportation Demand Management",
"Transportation Equipment Manufacturing",
"Transportation Infrastructure",
"Transportation Mode/Preference",
"Travel Services & Tour Operators",
"Tribal Identity",
"Trophic Redundancy",
"Trophic State",
"Tube, Barrel & Finger Sponges",
"Tundra",
"Tunicates",
"Turbidity",
"Turf Algae",
"Type of Government",
"Untapped Future Potential",
"Upwelling",
"Urban Abandonment",
"Urban Canopy Cover",
"Urban Forestry",
"Urban Green Space",
"Urban Habitat",
"Urban Identity",
"Urban Transportation Infrastructure",
"Urban Wildlife Species",
"Urbanization",
"Utilities",
"Utility Line Construction & Maintenance",
"Utility-Scale Photovoltaic (PV) Systems",
"Valuation",
"Values & Ethics",
"Vegetative Cover & Distribution",
"Viruses",
"Visitation of Beaches, Conservation Lands & Nature Parks",
"Visual Screening",
"Volatile Organic Compounds",
"Volatile Organic Compounds (VOC) Emission",
"Volcanos",
"Volume & Biomass",
"Voting Pattern",
"Vulnerability",
"Vulnerability to Crime",
"Vulnerability to Illness",
"Walking",
"Waste & Materials Management",
"Waste Collection",
"Waste Management",
"Waste Management Policies & Programs",
"Wastewater Discharge",
"Wastewater Management",
"Wastewater Treatment",
"Water",
"Water Clarity",
"Water Contaminants",
"Water Cycling",
"Water Depth & Sea Level",
"Water for Cooling or Processing Industrial Products",
"Water Purification & Waste Treatment",
"Water Quality",
"Water Quality Regulation",
"Water recharge rate",
"Water Regulation",
"Water Resources",
"Water Resources Management",
"Water Transportation",
"Water Use",
"Water Use for Industrial Processing or Cooling",
"Water Utilities & Management",
"Water Vapor (H2O) Emission",
"Water-Based Spatial Resources",
"Waterborne Discharges",
"Waterfront Destinations",
"Watershed Integrity",
"Wave Energy Attenuation",
"Wealth Disparity",
"Wetland Conversion",
"Wetlands Habitat",
"Wetlands Species",
"Whale Poaching or Harvest",
"Whales & Dolphins",
"Wholesale & Retail Trade",
"Wild Flowers",
"Wildfire Regulation",
"Wildlife Harassment",
"Wildlife Health, Disease & Bleaching",
"Wind",
"Wind Power",
"Wood & Paper Products",
"Wood, Plastics & Chemical Products",
"Youth Mentoring & Education Programs",
"Zooxanthellae"]

var toolIDs = {};

for (var toolID in toolCache.getCache()) {
	var title = toolCache.getCache()[toolID].data["Title"];
	var concepts = getToolConcepts(toolID);
	
	var uppercase = conc;
	var lowercase = uppercase.map(function(x){ return x.toLowerCase() });

	for (var i = 0; i < concepts.length; i++) {
		if (lowercase.includes(concepts[i])) {
			var idx = lowercase.indexOf(concepts[i]);
			concepts[i] = uppercase[idx];
        }
	}

	console.log(title);
	console.log(printArray(concepts));
	toolIDs[toolID] = 1;
}